learning_templates/basic_app/urls.py
from importlib.resources import path
from xml.etree.ElementInclude import include
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('relative/',views.relative_url,name = 'relative'),
    path('others/', views.others,name = 'others'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from basic_app import views
urlpatterns = [
    path('',views.index,name='index'),
    path('basic_app/',include('basic_app.urls')),
    
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':"hello jayant",'num':154}
    return render(request,'basic_app/index.html',context_dict)

def others(request):
    return render(request,'basic_app/others.html')

def relative_url(request):
    return render(request,'basic_app/relative_urls.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index'%}">Navbar</a>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'admin:index'%}">Admin <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:others'%}">others</a>
              </li>
            </ul>
         </div>
    </nav>

    <div class="container">
        {% block body_block %}

        {% endblock %}
    </div>
    
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>

    {% extends "basic_app/base.html" %}
    {% load my_extras %}
    {% block body_block %}
        <h1>Welcome to INDEX!</h1>
        <h2>{{ text|cut:'hello' }}</h2>
        <h2>{{ num|add:"154" }}</h2>
    {% endblock %}

learning_templates/templates/basic_app/others.html
<!DOCTYPE html>
    {% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcoem to others! </h1>
        <h2>Example of template inheritance</h2>

    {% endblock %}
    

learning_templates/templates/basic_app/relative_urls.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RELATIVE_URLS</title>
</head>
<body>
    <h1>Welcome to RELATIVE_URLS !</h1>
    <a href="{% url 'basic_app:others' %}">Blog</a>
</body>
</html>